# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
import numpy as np

In [8]:
### Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
rng = np.random.default_rng()
m = rng.integers(21,size=(5,5))
m[0:5,2:3] = 1
m

array([[ 1,  7,  1,  3,  3],
       [13, 13,  1,  4, 20],
       [12, 20,  1,  2,  5],
       [ 6,  1,  1, 14, 12],
       [20,  2,  1, 20, 14]])

In [12]:
m = np.random.randint(1,21,size=(5,5))
m[:,2] = 1
m

array([[ 4, 10,  1, 15, 15],
       [12,  5,  1,  2,  4],
       [ 5, 19,  1,  2,  5],
       [16, 12,  1, 19, 14],
       [10,  1,  1, 14, 14]], dtype=int32)

In [15]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
q2 = np.random.randint(1,17,size=(4,4))
np.fill_diagonal(q2,1)
q2


array([[ 1, 12, 10,  6],
       [ 7,  1, 12,  6],
       [16,  3,  1,  6],
       [ 8,  7,  9,  1]], dtype=int32)

In [18]:
### Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
q1 = np.random.randint(1,37,size=(6,6))
q1

array([[ 9, 12,  5, 20, 25, 31],
       [25, 15, 30,  2, 25, 13],
       [17,  3, 22, 25,  6,  4],
       [14, 18, 19, 29,  9, 27],
       [18, 15, 24, 14, 33, 35],
       [22, 28, 35, 10, 14, 10]], dtype=int32)

In [19]:
q1[2:5,1:4]

array([[ 3, 22, 25],
       [18, 19, 29],
       [15, 24, 14]], dtype=int32)

In [28]:
# #2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
q2 = np.random.randint(1,10,size=(5,5))
q2

array([[2, 6, 2, 1, 3],
       [3, 2, 7, 1, 7],
       [6, 8, 4, 6, 8],
       [8, 3, 4, 1, 3],
       [8, 6, 8, 4, 8]], dtype=int32)

In [29]:
q2[:,4]

array([3, 7, 8, 3, 8], dtype=int32)