# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
import numpy as np

In [8]:
### Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
rng = np.random.default_rng()
m = rng.integers(21,size=(5,5))
m[0:5,2:3] = 1
m

array([[ 1,  7,  1,  3,  3],
       [13, 13,  1,  4, 20],
       [12, 20,  1,  2,  5],
       [ 6,  1,  1, 14, 12],
       [20,  2,  1, 20, 14]])

In [12]:
m = np.random.randint(1,21,size=(5,5))
m[:,2] = 1
m

array([[ 4, 10,  1, 15, 15],
       [12,  5,  1,  2,  4],
       [ 5, 19,  1,  2,  5],
       [16, 12,  1, 19, 14],
       [10,  1,  1, 14, 14]], dtype=int32)

In [15]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
q2 = np.random.randint(1,17,size=(4,4))
np.fill_diagonal(q2,1)
q2


array([[ 1, 12, 10,  6],
       [ 7,  1, 12,  6],
       [16,  3,  1,  6],
       [ 8,  7,  9,  1]], dtype=int32)

In [18]:
### Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
q1 = np.random.randint(1,37,size=(6,6))
q1

array([[ 9, 12,  5, 20, 25, 31],
       [25, 15, 30,  2, 25, 13],
       [17,  3, 22, 25,  6,  4],
       [14, 18, 19, 29,  9, 27],
       [18, 15, 24, 14, 33, 35],
       [22, 28, 35, 10, 14, 10]], dtype=int32)

In [19]:
q1[2:5,1:4]

array([[ 3, 22, 25],
       [18, 19, 29],
       [15, 24, 14]], dtype=int32)

In [28]:
# #2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
q2 = np.random.randint(1,10,size=(5,5))
q2

array([[2, 6, 2, 1, 3],
       [3, 2, 7, 1, 7],
       [6, 8, 4, 6, 8],
       [8, 3, 4, 1, 3],
       [8, 6, 8, 4, 8]], dtype=int32)

In [29]:
q2[:,4]

array([3, 7, 8, 3, 8], dtype=int32)

In [2]:
### Assignment 3: Array Operations

#1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
n1 = np.random.randint(1,5,size=(3,4))
n2 = np.random.randint(1,5,size=(3,4))

In [3]:
n1

array([[2, 2, 2, 1],
       [3, 4, 4, 1],
       [1, 2, 3, 4]], dtype=int32)

In [4]:
n2

array([[3, 2, 1, 4],
       [1, 3, 1, 4],
       [2, 4, 4, 1]], dtype=int32)

In [6]:
#addition
n1+n2

array([[5, 4, 3, 5],
       [4, 7, 5, 5],
       [3, 6, 7, 5]], dtype=int32)

In [7]:
# multiplication
n1*n2

array([[ 6,  4,  2,  4],
       [ 3, 12,  4,  4],
       [ 2,  8, 12,  4]], dtype=int32)

In [8]:
# division
n1%n2

array([[2, 0, 0, 1],
       [0, 1, 0, 1],
       [1, 2, 3, 0]], dtype=int32)

In [ ]:
#subtraction
n1-n2

array([[-1,  0,  1, -3],
       [ 2,  1,  3, -3],
       [-1, -2, -1,  3]], dtype=int32)

In [9]:
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

q2 = np.random.randint(1,17,size=(4,4))
q2

array([[ 3, 10,  2, 12],
       [15,  1,  6,  3],
       [ 5, 11,  9, 16],
       [ 2, 16, 15,  5]], dtype=int32)

In [18]:
q21 = np.cumulative_sum(q2,axis=1)
q21

array([[ 3, 13, 15, 27],
       [15, 16, 22, 25],
       [ 5, 16, 25, 41],
       [ 2, 18, 33, 38]])

In [19]:
q22 = np.cumulative_sum(q2,axis=0)
q22

array([[ 3, 10,  2, 12],
       [18, 11,  8, 15],
       [23, 22, 17, 31],
       [25, 38, 32, 36]])

In [21]:
q2f = [q21[:,-1],q22[-1,:]]
q2f

[array([27, 25, 41, 38]), array([25, 38, 32, 36])]

In [22]:
## Or
row_sum = np.sum(q2,axis=1)
col_sum = np.sum(q2,axis=0)
print("Row sum" ,row_sum)
print("Column sum ",col_sum)

Row sum [27 25 41 38]
Column sum  [25 38 32 36]


In [32]:
### Assignment 4: Statistical Operations

#1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
n = np.random.randint(1,20,size=(5,5))
print(n)
sum = n.sum()
mean = n.mean()
variance = n.var()
std = np.sqrt(variance)
median = np.median(n)
print("Sum",sum)
print("Mean",mean)
print("variance",variance)
print("Std",std)
print("Median",median)

[[ 7 18 18  1 17]
 [15  1 19  1  8]
 [ 1 10  1  3 15]
 [ 7  1  7 11 13]
 [ 7  8 13 19 15]]
Sum 236
Mean 9.44
variance 40.166399999999996
Std 6.337696742508275
Median 8.0


In [38]:
#2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

n = np.random.randint(1,10,size=(3,3))
print(n)
mean = np.mean(n)
std = np.std(n)
normalised_array = (mean-n)/std
print(normalised_array)


[[8 8 5]
 [8 6 1]
 [7 5 7]]
[[-0.88618626 -0.88618626  0.52128604]
 [-0.88618626  0.0521286   2.39791576]
 [-0.41702883  0.52128604 -0.41702883]]


In [41]:
### Assignment 5: Broadcasting

#1. Create a NumPy array of shape (3, 3) filled with random integers. 
# Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
n1 = np.random.randint(1,10,size=(3,3))
print(n1)
n2 = np.array([11,12,13])

n1+n2


[[5 4 5]
 [6 8 4]
 [8 3 1]]


array([[16, 16, 18],
       [17, 20, 17],
       [19, 15, 14]])

In [43]:
#2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
n1 = np.random.randint(1,10,size=(3,3))
print(n1)
n2 = np.array([11,12,13])

abs(n1-n2)


[[3 5 8]
 [6 6 9]
 [1 8 5]]


array([[ 8,  7,  5],
       [ 5,  6,  4],
       [10,  4,  8]])

In [45]:
### Assignment 6: Linear Algebra

#1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
n = np.random.randint(1,10,size=(3,3))
print(np.linalg.det(n))
print(np.linalg.inv(n))
print(np.linalg.eig(n))

74.99999999999997
[[-2.00000000e-01  2.37904934e-17  2.00000000e-01]
 [-2.80000000e-01 -4.00000000e-01  4.80000000e-01]
 [ 5.60000000e-01  4.66666667e-01 -6.26666667e-01]]
EigResult(eigenvalues=array([15.32333115, -5.42034485, -0.90298629]), eigenvectors=array([[-0.54663579, -0.66298454, -0.17237077],
       [-0.41899886,  0.74686551, -0.59886799],
       [-0.72500294, -0.0514141 ,  0.78207765]]))


In [49]:
#2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
n1 = np.random.randint(1,5,size=(2,3))
n2 = np.random.randint(6,10,size=(3,2))
print(n1)
print(n2)
op = np.matmul(n1,n2)
print(op)

[[1 1 3]
 [2 4 4]]
[[7 8]
 [6 8]
 [7 7]]
[[34 37]
 [66 76]]


In [53]:
### Assignment 7: Advanced Array Manipulation

#1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
n1 = np.random.randint(1,10,size=(3,3))
print(n1)
n2 = n1.reshape(1,9)
print(n2)
n3 = n2.reshape(9,1)
print(n3)

[[8 7 1]
 [4 2 2]
 [4 6 1]]
[[8 7 1 4 2 2 4 6 1]]
[[8]
 [7]
 [1]
 [4]
 [2]
 [2]
 [4]
 [6]
 [1]]


In [57]:
#2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
n1 = np.random.randint(1,10,size=(5,5))
print(n1)
n2 = n1.flatten()
print(n2)
n3 = n2.reshape(5,5)
print(n3)

[[1 8 4 4 5]
 [1 2 1 2 9]
 [3 1 8 4 4]
 [9 3 3 3 4]
 [5 1 9 3 5]]
[1 8 4 4 5 1 2 1 2 9 3 1 8 4 4 9 3 3 3 4 5 1 9 3 5]
[[1 8 4 4 5]
 [1 2 1 2 9]
 [3 1 8 4 4]
 [9 3 3 3 4]
 [5 1 9 3 5]]


In [8]:
### Assignment 8: Fancy Indexing and Boolean Indexing

#1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
n1 = np.random.randint(1,10,size=(5,5))
print(n1)
top_left = n1[0, 0]
top_right = n1[0, -1]
bottom_left = n1[-1, 0]
bottom_right = n1[-1, -1]

corners = [top_left, top_right, bottom_left, bottom_right]
print("Corner elements:", corners)


[[2 7 4 4 5]
 [4 4 2 9 9]
 [2 5 8 3 9]
 [3 5 6 7 2]
 [3 3 5 2 7]]
Corner elements: [np.int32(2), np.int32(5), np.int32(3), np.int32(7)]


In [17]:
#2. Create a NumPy array of shape (4, 4) filled with random integers. 
# Use boolean indexing to set all elements greater than 10 to 10.
import numpy as np

n2 = np.random.randint(1, 10, size=(4, 4))
print("Matrix:\n", n2)

# Create a boolean mask with the same shape
mask = np.zeros_like(n2, dtype=bool)

# Set corners to True
mask[0, 0] = True                      # top-left
mask[0, -1] = True                     # top-right
mask[-1, 0] = True                     # bottom-left
mask[-1, -1] = True                    # bottom-right

# Apply the mask
corners = n2[mask]
print("Corner elements:", corners)


Matrix:
 [[9 8 3 9]
 [4 4 6 2]
 [8 6 3 4]
 [3 1 8 6]]
Corner elements: [9 9 3 6]
